# Generated by Django 4.2.1 on 2024-03-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('position', models.CharField(max_length=255, verbose_name='status')),
                ('organisation', models.CharField(max_length=255, verbose_name='organisation_name')),
            ],
            options={
                'verbose_name': 'EducationWork',
                'verbose_name_plural': 'EducationWork',
                'ordering': ['date'],
            },
        ),
    ]
