# Generated by Django 4.2.1 on 2024-03-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identificators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wos_index', models.CharField(max_length=20, verbose_name='wos_index')),
                ('scopus_index', models.CharField(max_length=20, verbose_name='scopus_index')),
                ('orcid', models.CharField(max_length=20, verbose_name='orcid')),
                ('e_lib_index', models.CharField(max_length=20, verbose_name='e_lib_index')),
            ],
            options={
                'verbose_name': 'Identificators',
                'verbose_name_plural': 'Identificators',
            },
        ),
        migrations.CreateModel(
            name='ProjectsParticipate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=400, verbose_name='project_title')),
                ('foundation', models.CharField(max_length=300, verbose_name='foundation')),
                ('project_number', models.CharField(max_length=50, verbose_name='project_number')),
                ('project_years', models.CharField(max_length=150, verbose_name='project_years')),
            ],
            options={
                'verbose_name': 'ProjectsParticipate',
                'verbose_name_plural': 'ProjectsParticipate',
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=355, verbose_name='article_title')),
                ('authors', models.CharField(max_length=555, verbose_name='article_title')),
                ('doi', models.URLField(verbose_name='doi')),
                ('wos', models.BooleanField()),
                ('scopus', models.BooleanField()),
                ('e_library', models.BooleanField()),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Publications',
                'verbose_name_plural': 'Publications',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='SkillCategory')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'SkillCategory',
                'verbose_name_plural': 'SkillCategory',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=500, verbose_name='Skill')),
                ('skill_cat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='title.skillcategory', verbose_name='skill_cat')),
            ],
            options={
                'verbose_name': 'Skills',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
