# Generated by Django 4.2.1 on 2024-03-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0002_identificators_projectsparticipate_publications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identificators',
            name='e_lib_index',
        ),
        migrations.RemoveField(
            model_name='identificators',
            name='orcid',
        ),
        migrations.RemoveField(
            model_name='identificators',
            name='scopus_index',
        ),
        migrations.RemoveField(
            model_name='identificators',
            name='wos_index',
        ),
        migrations.AddField(
            model_name='identificators',
            name='number',
            field=models.CharField(default=1, max_length=30, verbose_name='index_number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identificators',
            name='type',
            field=models.CharField(default=1109, max_length=40, verbose_name='index_type'),
            preserve_default=False,
        ),
    ]
