# Generated by Django 4.2.1 on 2024-03-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0003_remove_identificators_e_lib_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='journal',
            field=models.CharField(default=' ', max_length=400, verbose_name='journal'),
        ),
        migrations.AddField(
            model_name='publications',
            name='quartile',
            field=models.IntegerField(default=1, verbose_name='quartile'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='year',
            field=models.IntegerField(verbose_name='year'),
        ),
    ]
