# Generated by Django 4.2.1 on 2024-03-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0004_publications_journal_publications_quartile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationwork',
            name='date',
            field=models.CharField(max_length=20, verbose_name='Date'),
        ),
    ]
