# Generated by Django 4.2.1 on 2024-03-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0005_alter_educationwork_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsparticipate',
            name='project_years',
        ),
        migrations.AddField(
            model_name='projectsparticipate',
            name='project_year_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='project_year_end'),
        ),
        migrations.AddField(
            model_name='projectsparticipate',
            name='project_year_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='project_year_start'),
        ),
    ]
