# Generated by Django 4.2.1 on 2024-03-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0006_remove_projectsparticipate_project_years_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsparticipate',
            options={'ordering': ['-project_year_end'], 'verbose_name': 'ProjectsParticipate', 'verbose_name_plural': 'ProjectsParticipate'},
        ),
        migrations.AddField(
            model_name='educationwork',
            name='last_actual_year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
