# Generated by Django 4.2.1 on 2024-03-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0007_alter_projectsparticipate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationwork',
            options={'ordering': ['-last_actual_year'], 'verbose_name': 'EducationWork', 'verbose_name_plural': 'EducationWork'},
        ),
        migrations.AddField(
            model_name='educationwork',
            name='type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='educationwork',
            name='last_actual_year',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='last_actual_year'),
        ),
    ]
