# Generated by Django 5.0.4 on 2024-05-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("title", "0008_alter_educationwork_options_educationwork_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skills",
            options={
                "ordering": ["skill_cat"],
                "verbose_name": "Skills",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.AlterField(
            model_name="publications",
            name="quartile",
            field=models.IntegerField(
                blank=True, default=1, null=True, verbose_name="quartile"
            ),
        ),
    ]
