# Generated by Django 5.0.4 on 2024-06-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("title", "0009_alter_skills_options_alter_publications_quartile"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationwork",
            name="organisation_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="organisation_name_en",
            ),
        ),
        migrations.AddField(
            model_name="educationwork",
            name="position_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="position_en"
            ),
        ),
        migrations.AddField(
            model_name="projectsparticipate",
            name="foundation_en",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="foundation_en"
            ),
        ),
        migrations.AddField(
            model_name="projectsparticipate",
            name="project_title_en",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="project_title_en"
            ),
        ),
        migrations.AlterField(
            model_name="educationwork",
            name="position",
            field=models.CharField(max_length=255, verbose_name="position"),
        ),
    ]
