# Generated by Django 5.0.4 on 2024-06-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("title", "0010_educationwork_organisation_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationwork",
            name="type_en",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="type_en"
            ),
        ),
        migrations.AlterField(
            model_name="educationwork",
            name="last_actual_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="last_actual_year"
            ),
        ),
    ]
