# Generated by Django 5.0.4 on 2024-07-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("title", "0011_educationwork_type_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawWorkExamples",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="DrawExample"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=800, verbose_name="DrawExample_desc"),
                ),
                (
                    "img_file",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="draw_works/",
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "DrawWorkExamples",
                "verbose_name_plural": "DrawWorkExamples",
            },
        ),
    ]
