# Generated by Django 5.0.4 on 2024-07-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("title", "0012_drawworkexamples"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawworkexamples",
            name="img_file",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="draw_works/",
                verbose_name="draw_works_img",
            ),
        ),
    ]
