# Generated by Django 5.0.4 on 2024-07-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("title", "0013_alter_drawworkexamples_img_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawworkexamples",
            name="img_file",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="work_examples/",
                verbose_name="draw_works_img",
            ),
        ),
    ]
